const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  ABOUT: "/aboutUsPage",
  EDITGAME: "/editgame",
  CREATEGAME: "/creategame",
  SANDBOX: "/sandbox",
  MYGAMES: "/mygames",
  CATEGORY: "/category",
  FAV: "/fav",
  DETAILS: "/detalis",
  PROFILE: "/profile",
  EDITUSER: "/edituser",
  ADMIN: "/admin",
  FORGETPASS: "/forgetpass",
  RESETPASSWORD: "/reset_password/:id/:token",
  CONTACT: "/contact",
  PAGEHEADER: "/pagehead",
  CART: "/cart",
};
export default ROUTES;
